version: "3.4"

services:
  fastapi:
    image: mohamedwassim123564/time-management-fastapi:latest
    container_name: fastapi
    environment:
      - FASTAPI_URL=http://fastapi:8000
    networks:
      - app-network
    restart: unless-stopped

  express:
    image: mohamedwassim123564/time-management-express:latest
    container_name: express
    ports:
      - "5000:5000"
    environment:
      - FASTAPI_URL=http://fastapi:8000
    networks:
      - app-network
    depends_on:
      - fastapi
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
